### ISSUE TITLE
Exception loading example-all.jar with termux

### ISSUE THREAD

**Issue by Timeree** [gudzpoz/luajava#126]
An error occurred while loading the example-all.jar using [termux]. Here is the complete information:
![Screenshot_2023-10-18-20-48-59-237_com termux](https://github.com/gudzpoz/luajava/assets/128987712/2e6f30fb-0423-4125-a457-26697e4a4ccb)

I am a novice and ask for help.

**Comment by gudzpoz** [comment]
Before asking for help by opening an issue, you should first learn to search for your issue: https://github.com/gudzpoz/luajava/issues?q=termux . And you will see it is already answered there.
Dup #86
