### ISSUE TITLE
Conversion from lua table to java map use wrong index

### ISSUE THREAD

**Issue by MaxThlon** [gudzpoz/luajava#127]
Hello.
Conversion from lua table to java map use wrong index to call C.lua_next(L, -2)
in AbstractLua.java line 384 [C.lua_next(L, -2)](https://github.com/gudzpoz/luajava/blob/main/luajava/src/main/java/party/iroiro/luajava/AbstractLua.java#L384)  is missing index,  one solution is
  /* Use positive index or  values under LUA_REGISTRYINDEX(-10000), or  decrement negative index */
  C.lua_next(L, ((index > 0) || (index  < -9999))? index  : (index -1))

or the other solution is to pushValue(index) when stack is at the same state and re pushValue(...) for the lua_next call.

Otherwise it's work pretty well, cool project, thanks for the hard work.

**To Reproduce**
L.createTable(0, 2);
L.push("AA");
L.setField(-2, "A");
L.pushNil();  /* dumb value to fill the stack */
Map<?, ?> map = L.toMap(-2); /* will crash */
assert(!map.isEmpty());  /* will fail */
L.pop(2)

**Platform:**
- Arch: x86_64
 - OS: windows
 - Lua Version: Lua 5.1

**Comment by gudzpoz** [comment]
Thank you for reporting! A new version `3.5.0` with the fix should have been published on Maven Central.
