### ISSUE TITLE
Support for Android Studio.

### ISSUE THREAD

**Issue by leasses** [gudzpoz/luajava#14]
It was a bit complicated. I add the dependencies to my `build.gradle` file, just like this:
```
implementation 'party.iroiro.luajava:luajava:3.0.2'
implementation 'party.iroiro.luajava:luajit:3.0.2'
implementation 'party.iroiro.luajava:luajit-platform:3.0.2:natives-armeabi-v7a'
implementation 'party.iroiro.luajava:luajit-platform:3.0.2:natives-arm64-v8a'
```
But the Gradle didn't add the `.so` files to my APK. So when I run the app on my phone, It exits and throws an Expection: 
```
java.lang.UnsatisffiedLinkError: Unable to find natives or init.
```
So I try to move the `.so` files to `jniLibs\<target API>\` directory, but it still can't work and throws the Expection.

What should I do?

**Comment by gudzpoz** [comment]
I added [some documentation about Android configurations](https://gudzpoz.github.io/luajava/getting-started.html#android). Can you try again with `3.0.3-SNAPSHOT`?

```groovy
repositories {
    maven {
        url 'https://s01.oss.sonatype.org/content/repositories/snapshots/'
    }
}

ext {
    lua = 'luajit'
    luaJavaVersion = '3.0.3-SNAPSHOT'
}
```

**Comment by leasses** [comment]
I tried, but it still can't work. My app only have these codes:
```java
package leasses.app.zuie;

import party.iroiro.luajava.LuaJit;

public class LuaActivity extends AppCompatActivity {
    private LuaJit L;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        try {
            L = new LuaJit();
        } catch (UnsatisfiedLinkError e) {
            Log.e("LuaJIT", e.toString());
        }
    }
}
```
Although I add a try-catch block, the app still exit automatically.
This is the log:
``` 
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x36fffb8074a9 in tid 21746 (com.example.app), pid 21746 (com.example.app)
```
It seems it's a native error.
What should I do to fix it?

**Comment by leasses** [comment]
I tried, but it still can't work. My app only have these codes:
```java
package leasses.app.zuie;

import party.iroiro.luajava.LuaJit;

public class LuaActivity extends AppCompatActivity {
    private LuaJit L;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        try {
            L = new LuaJit();
        } catch (UnsatisfiedLinkError e) {
            Log.e("LuaJIT", e.toString());
        }
    }
}
```
Although I add a try-catch block, the app still exit automatically.
This is the log:
``` 
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x36fffb8074a9 in tid 21746 (com.example.app), pid 21746 (com.example.app)
```
It seems it's a native error.
What should I do to fix it?

**Comment by gudzpoz** [comment]
Are you using version `3.0.3-SNAPSHOT` or `3.0.2`? Indeed, native binaries for version `3.0.2` lead to segment fault due to misconfigured build scripts, which hopefully has been fixed by `3.0.3-SNAPSHOT`.

**Comment by leasses** [comment]
Thanks so much for helping. It works!
And I give you an advice, you can use the `.aar` file to package it so that the Gradle can package the `.so` files to the APK instead of using the gradle scripts, and the configuration for Android can be shorter.
Of coures you can continue using `.jar` file, and its size is smaller than `.aar` file.

By the way, sorry for my poor English because I am Chinese. If you can understand Chinese, please tell me.

**Comment by gudzpoz** [comment]
Thanks for the suggestion! With #16, you can now include the native binaries with:
```groovy
implementation 'party.iroiro.luajava:luajit:3.0.3-SNAPSHOT'
runtimeOnly "party.iroiro.luajava:android:3.0.3-SNAPSHOT:luajit@aar"
```

**Comment by leasses** [comment]
Thank you!
