### ISSUE TITLE
Feat: More convenient grammar support

### ISSUE THREAD

**Issue by fuqiuluo** [gudzpoz/luajava#154]
I think the current API for Java operations is too complex, and the following operations can be achieved by modifying `llex. c`:

```lua
import "java.lang.System"

System.out.println("Hello wolrd~")
```

Reference project: https://github.com/nirenr/luaj

**Comment by gudzpoz** [comment]
No. This library is intended to be a lightweight wrapper around Lua C API, and maintaining a patch to Lua itself is simply out of scope.
