### ISSUE TITLE
Require function not available

### ISSUE THREAD

**Issue by jsorel** [gudzpoz/luajava#157]
**Describe the bug**
I am working on IHO S-100 specifications, in those specifications, LUA 5.1 is the scripting language for all rendering processes.
there are multiple lua files (about 200) which are loaded using the **require** function.
Some are loaded at the begining of the file like this `require 'S100Scripting'` and some later on with `require(feature.Code)`.

No lua module() are used, nowhere.

I made a small test case:
**To Reproduce**
Place the following files in the resources of the project :
**Friend2.lua**
```
require 'Friend3'

function tchat()
    return 'Hello ' .. anotherHello()
end
```

**Friend3.lua**
```
function anotherHello()
    return 'you'
end
```
And in java execute : 
```
try (final Lua lua = new Lua51()) {
    lua.setExternalLoader(new ClassPathLoader());
    Lua.LuaError error = lua.loadExternal("Friend2"); //OK
    LuaValue fct = lua.get(); //the loaded chunk as a function
    LuaValue[] result = fct.call(); //null -> so there is an error
    System.out.println(lua.status()); // OK ???
    System.out.println(lua.get().toJavaObject()); // [string "Friend2"]:1: attempt to call global 'require' (a nil value)
}
```

**Current behavior**
I could not find the 'require' function, even with `local require = require`.

**Expected behavior**
Is require usable in LuaJava ? 
Must I implement it ? how ?

**Platform:**
- Arch:x86_64
 - OS: Linux
 - Lua Version: Lua 5.1

**Additional context**

**Comment by AMCON-Chenet** [comment]
You are missing an 'import' of the default lua libraries.
Try calling this before setting the externalLoader.
```
lua.openLibraries()
```

**Comment by jsorel** [comment]
I knew something wasn't right, I couldn't call any of the string functions either.

Many thanks,
