### ISSUE TITLE
Custom modules

### ISSUE THREAD

**Issue by Trivaxy** [gudzpoz/luajava#165]
I'm working on integrating LuaJava to one of my projects. To keep things clean, a lot of the functionality implemented on the Java side is (meant to be) exposed to the Lua side in the form of custom modules, e.g
```lua
local geom = require("geometry")
local world = require("world")
...
```
I've seen `setExternalLoader` and `loadExternal`, but those don't seem to be what I need as these modules are entirely implemented on the Java side. Any advice?

**Comment by gudzpoz** [comment]
You may use [Java method modules] https://gudzpoz.github.io/luajava/examples/modules.html#java-method-modules for that.

**Comment by Trivaxy** [comment]
I see. Is it possible to alias the module name to something simpler for the users?
i.e `require("world")` instead of `require("xyz.trivaxy.modules.MyModule.open")`

**Comment by gudzpoz** [comment]
LuaJava does not provide a builtin way to do this. But you can of course rewrite the `require` function as you wish:

```lua
local oldRequire = require
local mapping = {
    shortname = "xyz.trivaxy.modules.MyModule.open",
}
function require(name)
    return oldRequire(mapping[name] or name)
end
```

**Comment by Trivaxy** [comment]
Yeah, that's a good way to do it. Thanks.
