### ISSUE TITLE
ClassNotFoundException When Importing a Java Class in LuaJava

### ISSUE THREAD

**Issue by Keurig-Creator** [gudzpoz/luajava#200]
**Describe the Bug**
I am encountering a ClassNotFoundException when attempting to import a Java class into Lua using LuaJava within a Spigot plugin. The error occurs even though the class path appears to be correct, as evidenced by a hyperlink in the console that directly opens the class. The issue is not related to Android, as I am not using it.

**To Reproduce**

Set up a Spigot plugin project with LuaJava as a dependency.

Use the following LuaJava code to import a Java class:
```java
try (Lua lua = new Lua51()) {
    lua.openLibraries();
    lua.run("Chat = java.import('com.keurig.luaplugin.Chat')");
    lua.run("Chat:log('Test from lua')");
} catch (Exception e) {
    e.printStackTrace();
}
```
Run the plugin and observe the ClassNotFoundException in the console.

Verify the com.keurig.luaplugin.Chat class is present in the project and accessible.

**Current Behavior**
The ClassNotFoundException is thrown despite the class being present and the class path seemingly correct. The error does not provide any clear indication of why the class cannot be found.

**Expected Behavior**
The class com.keurig.luaplugin.Chat should be successfully imported into Lua, allowing the script to interact with the class as expected.

**Platform**

Arch: x86_64
OS: Windows 11
JDK: 17
Gradle Version: 8.10
LuaJava Version: 4.0.1
Spigot Version: 1.21
Additional Context:
I am using Gradle for this project. Here is my build.gradle configuration:
[Link to build.gradle:](https://hastebin.com/share/jucibuqomu.python)

This issue may be related to how LuaJava handles class loading, potentially involving the system classloader. I have reviewed several resources, including those specific to Android, but I am not using Android for this project.

Thank you for your assistance in resolving this issue.

**Comment by gudzpoz** [comment]
I just release a v4.0.2 with a fix, can you please try it out?

Also, when debugging I discovered that the Gradle plugin `shadow` does not prune `META-INF/versions/9/module-info.class` from the dependencies, which might still cause problems. So you might want to find a way to exclude these `module-info.class` with some `shadow` options. (https://gudzpoz.github.io/luajava/troubleshooting.html#are-you-mistakenly-using-java-9-modules)
