### ISSUE TITLE
[QUESTION]How to Call a Lua Function from Java?

### ISSUE THREAD

**Issue by leasses** [gudzpoz/luajava#24]
In the orgin luajava, there is a class `LuaFunction`, and I can call it by its method `_call`.
But I did't find this in your luajava. Maybe I missed, could you please tell me how to do? Thanks!

And, thanks so much for you contribution of this project. I am sure this is the best luajava in all of I knows. ❤

**Comment by gudzpoz** [comment]
You may use the new [LuaValue API](https://gudzpoz.github.io/luajava/examples/java.html#luavalue-interface).

```java
L.run("return function(str) print('Hello ' .. str) end");
try (LuaValue function = L.get()) {
    function.call("World");
}
```

**Comment by leasses** [comment]
Thanks!
