### ISSUE TITLE
[Enhancement] Query deeply nested inner classes with a better syntax

### ISSUE THREAD

**Issue by leasses** [gudzpoz/luajava#25]
Now, if I want to call an inner calss, I need to import it with java.import.
Android provided a class`R` to save the resources, and it has a lot of inner class such as `id`, `mipmap`, `string`, `style`, `drawable`...
So if I can only import the `R` class and use `R.id`, `R.mipmap`, `R.string`... to assert them, the code length will be much shorter, and very useful!
Tip: There is already somebody implement this function, you can have a look [Androlua Pro][https://github.com/nirenr/androlua_pro]. But it had an fatal bug: it cannot much the method by the arguments. So it's efficiency is very low.

**Comment by gudzpoz** [comment]
For direct inner classes, you may try the following:

```lua
R = java.import('android.R.*')

-- java.import('android.R.id').input
print(R.id.input)
```

However, this will not work for inner classes nested any further: `R.inner1.inner1Inner2` requires manual import again.

As for now, I cannot think of a better way to do this. Consider a class `ClassA` with an inner class `Inner` AND a method `Inner`: (Yes, it is totally possible in Java.)

```java
public class ClassA {
    public static class Inner {
    }
    public static void Inner() {}
}
```

The following Lua code would become ambiguous had we supported deeply nested inner classes:

```lua
ClassA = java.import('com.example.ClassA')
-- What should we do?
-- Does the user want a class or a method?
print(ClassA.Inner)
```

**Comment by leasses** [comment]
I am sorry for my poor English. And it's hard to input the special symbols on the phone, so it's a little hard to read.

Fist, as for me(the user), if I want to assert the inner class, I will ise this code:
ClassA.Inner()
But, if I want to call an method, I will use this one:
ClassA:Inner()
Do you see the differents between them?
So, you can add a judgement, if the first argument is self, calls the method, else, returns the class.
But, maybe method just need itself as the first argument...but that situation is very rare.
Thanks!

**Comment by leasses** [comment]
Oops! I missed something important.
The java also allows a field with the same name of the inner class.
So...it seems that's a really difficult problem.

**Comment by leasses** [comment]
Sorry, but I really need this function.
There are many inner classes with the same name. For example, many progrems uses the Builder Pattern, so they almost all have an inner class `Builder`, it can happen in many classes, like `okhttp.Request$Builder`, `android.app.AlertDialog$Builder`. If I import them one by one, it's surely very fussy.
I discuss with my friends, and summy a plan:
1. If the user uses `ClassA:Inner()`, just retuen the method.
2. If the user uses the `ClassA.Inner`, just return the field, no matter there is an inner class `ClassA$Inner` (Because my friends think it's easier to implement, of course you can retuen the inner class if it's easier to implement).
3. If there is not field `Inner` in `ClassA`, return the inner class.

**Comment by leasses** [comment]
Sorry, but I really need this function.
There are many inner classes with the same name. For example, many progrems uses the Builder Pattern, so they almost all have an inner class `Builder`, it can happen in many classes, like `okhttp.Request$Builder`, `android.app.AlertDialog$Builder`. If I import them one by one, it's surely very fussy.
I discuss with my friends, and summy a plan:
1. If the user uses `ClassA:Inner()`, just retuen the method.
2. If the user uses the `ClassA.Inner`, just return the field, no matter there is an inner class `ClassA$Inner` (Because my friends think it's easier to implement, of course you can retuen the inner class if it's easier to implement).
3. If there is not field `Inner` in `ClassA`, return the inner class.

**Comment by gudzpoz** [comment]
Yes, after some reconsideration, since the vast majority of the Java code base uses CamelCase naming, the chance of name collision is pretty low.

I shall summarize the lookup cascade as follows:

1. `SomeClass.ABC` searches for a `static` field named `ABC`, if found, it returns the field.
2. If no such field is present, it looks for an inner class named `ABC`, and returns directly if it is found.
   - If an inner class is indeed hidden by a field with the same name, (which is unlikely), one can still retrieve the class with `java.import`.
3. If no field or inner class is found, it defaults to a method call.

For the following class:
```java
public class A {
    public static String B = "B";
    public static class B {
    }
    public static class C {
    }
    public static void C() {}
    public static void d() {}
}
```

the following Lua snippet is interpreted as:
```lua
A = java.import('A')
print(A.B) -- "B"
print(A.C) -- userdata: the inner class C
print(A.d) -- function

-- Flexibility is ensured with:
B = java.import('A.B')
C = java.method(A, 'C')
```

**Comment by gudzpoz** [comment]
Implemented in https://github.com/gudzpoz/luajava/commit/57a6b48f2b65683aca727697d0ee7123a755028e .
