### ISSUE TITLE
[ENHANCEMENT]Create a Proxy of an Interface with Better Syntax.

### ISSUE THREAD

**Issue by leasses** [gudzpoz/luajava#26]
Now, to proxy an interface `Interface`, need to use java.proxy(Interface, ...).
But it's a little verbose. Can just call it with a table?
Jist like this:
Interface({...})
Hope you reply. 😊

**Comment by gudzpoz** [comment]
Implemented. Thanks!

```lua
java.import('java.lang.Runnable')({ run = function() print('Hello') end }):run()
```
