### ISSUE TITLE
[Improvement] detailed error message on LinkageError

### ISSUE THREAD

**Issue by AMCON-Chenet** [gudzpoz/luajava#27]
We are getting NativeLinkErrors when calling Lua54 from our Jenkins build server and can't pinpoint the cause.

- local windwos builds work
- arm android builds work 
- linux jenkins doesn't work

I think it would be good to change the UnsatisfiedLinkError to an LinkageError and pass the inner exception to it.

https://github.com/gudzpoz/luajava/blob/4308143f4ff5ddcbe8b788201cac8c509a8c34d8/lua54/src/main/java/party/iroiro/luajava/Lua54.java#L32)

PS: i would make a PR but first i have to get my developement enviroment up to date to modify this project myself :)

**Comment by gudzpoz** [comment]
Thanks! I have changed from `UnsatisfiedLinkError` to `LinkageError`.

**Comment by AMCON-Chenet** [comment]
Hey, thanks to the change we could find the error.

Our build-setup runs on an GLIBC_2.26 enviroment.

`Caused by: java.lang.UnsatisfiedLinkError: /tmp/libgdxec2-user/6fc815ec/liblua5464.so: /lib64/libm.so.6: version \GLIBC_2.29\ not found (required by /tmp/libgdxec2-user/6fc815ec/liblua5464.so)`

Would it be possible for you to build the natives against a lower glibc version? 
If not could you point me to the changes I'd have to make to compile the files myself.

**Comment by gudzpoz** [comment]
Thanks for reporting! The snapshot binaries should now be working with lower glibc versions and I will soon do a `v3.1.2` release.

**Comment by AMCON-Chenet** [comment]
The release works fine. 👍
