### ISSUE TITLE
Error when trying to run the Hello World example on a modular Java project (Java  9+)

### ISSUE THREAD

**Issue by rsribeiro** [gudzpoz/luajava#43]
When trying to run the [Hello World](https://gudzpoz.github.io/luajava/examples/hello-world.html) example on a modular Java project, I'm encountering the following error:

`The package party.iroiro.luajava is accessible from more than one module: lua54, luajava`

This is my `module-info.java`, which contains automatic derived module names for the two maven dependencies I need to include:
```
module test {
    //Maven dependency 'luajava'
    requires luajava;
    //Maven dependency 'lua54'
    requires lua54;
}
```

This is the code:

```
import party.iroiro.luajava.Lua;
import party.iroiro.luajava.Lua54;

public class Test {
    public static void main(String[] args) {
        try (Lua L = new Lua54()) {
            L.openLibraries();
            L.run("System = java.import('java.lang.System')");
            L.run("System.out:println('Hello World from Lua!')");
        }
    }
}
```

From what I understand, in order to work with the new modular approach, you can't have the same package name `party.iroiro.luajava` defined in two different modules.

**Comment by gudzpoz** [comment]
Thanks for reporting! It seems that I need to split the package into several to adapt to the new modular approach in Java.

The change itself is trivial but is a breaking change after all, and it can take a while before I get the time to migrate all the tests and add some new ones regarding modular access. I might be able to get to this issue the next week. Sorry for the inconvenience!
