### ISSUE TITLE
Add MacOsX ARM64 build

### ISSUE THREAD

**Issue by chendler** [gudzpoz/luajava#61]
Thank you for the project. It is really handy to work with.

I want to propose to extend desktop platforms support with MacOsX arm64 architecture. Latest GitHub macos environment supports cross-compile. The only downside that it is not possible to run CI test against MacOsX arm64, but other than that result binary files seems to work fine.

Here is a pull request #60

**Comment by gudzpoz** [comment]
A new version v3.4.0 has been release incorporating the change. Thanks again!
