### ISSUE TITLE
Does the luajit version has the memory limit ???

### ISSUE THREAD

**Issue by lingbl** [gudzpoz/luajava#79]
The AMD64 version luajit has limit of 2G memory , does luajava has the same limit ???

**Comment by gudzpoz** [comment]
Short answer: No.

Longer answer: I suppose you should be able to Google things up or just test it yourself before posting an issue. LuaJIT used to have such a limit, which has been resolved with the new GC64 mode, which is now enabled by default.

Reference: https://blog.openresty.com/en/luajit-gc64-mode/#fn:4
