### ISSUE TITLE
How to choose the luajit ??

### ISSUE THREAD

**Issue by lingbl** [gudzpoz/luajava#80]
java -jar example-all.jar  -l luajit
java -jar example-all.jar  -l Luajit
java -jar example-all.jar  -l LuaJit
java -jar example-all.jar  -l jit
java -jar example-all.jar  -l Jit

no one is work , I test under windows

**Comment by lingbl** [comment]
I know want happened : 
    java -jar example-all.jar -e "print()" -l jit

**Comment by gudzpoz** [comment]
Implemented in https://github.com/gudzpoz/luajava/commit/85d66304c47036df6fa359498e4432b0c2326422
